## Exercise 1: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [12]:
import numpy as np
lst = [1,2,3,4,5,6,7,8]
tpl = ((8,4,6),(1,2,3))

lst_to_array= np.array(lst)
tpl_to_array = np.array(tpl)

print('list to array: ',lst_to_array)
print('type(list to array): ',type(lst_to_array))

print('tpl_to_array: ' ,tpl_to_array)
print('Type of tpl_to_array: ' ,type(tpl_to_array))


list to array:  [1 2 3 4 5 6 7 8]
type(list to array):  <class 'numpy.ndarray'>
tpl_to_array:  [[8 4 6]
 [1 2 3]]
Type of tpl_to_array:  <class 'numpy.ndarray'>


In [ ]:
import numpy as np
lst = [1,2,3,4,5,6,7,8]
tpl = ((8,4,6),(1,2,3))

lst_to_array= np.array(lst)
tpl_to_array = np.array(tpl)

print('list to array: ',lst_to_array)
print('type(list to array): ',type(lst_to_array))

print('tpl_to_array: ' ,tpl_to_array)
print('Type of tpl_to_array: ' ,type(tpl_to_array))


## Also try np.asarray for the problem above! 

## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [23]:
inp = [0,12,45.21,34,99.91]
f = np.array(inp)
c= (5*(f-32))/9
print('Values in  Centigrade degrees: ', f)
print('Values in Fahrenheit degrees: ', c)

Values in  Centigrade degrees:  [ 0.   12.   45.21 34.   99.91]
Values in Fahrenheit degrees:  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [36]:
inp = np.array([1,2,3])
print('Size of the array:',inp.size)
print('Length of one array element in bytes: ',inp.itemsize)
print('Total bytes consumed by the elements of the array: ',inp.nbytes)

Size of the array: 3
Length of one array element in bytes:  4
Total bytes consumed by the elements of the array:  12


## Exercise 4: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [46]:
a=np.array([10 ,10, 20 ,20, 30 ,30])
print('Unique elements of the above array:', np.unique(a))
a1=np.array([[1,1],[2,3]])
print('Unique elements of the above array:', np.unique(a1))

Unique elements of the above array: [10 20 30]
Unique elements of the above array: [1 2 3]


## Exercise 5: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
a=np.array(range(1,10))
print('Original array: ',a)
print('Change array shape to (3, 3)',a.reshape(3,3))

Original array:  [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [76]:
print(np.linspace(2.5,6.5,30))

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

In [84]:
Array1 = np.array([10, 20, 30])
Array2= np.array([40 ,50, 60])
a=np.column_stack((Array1,Array2))
print(a)

[[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [96]:
a=np.zeros([5,5])
b=np.array(range(5))
print('Original Array:',a)
print('Row values ranging from 0 to 4:',a+b)

Original Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4: [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [132]:
a=np.arange(1,100)
b= a[(a%3==0) | (a%5==0)]
print(b)
b.sum()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


2318

## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [135]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [161]:
a=np.arange(4)
print(a)
b=np.arange(8).reshape([2,4])
print(b)
for i,j in np.nditer([a,b]):
    print(i,':',j)

[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [227]:
a= np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581 , 0.34528799 ,0.1563123 ]])
print('original array:',a)
a[a>0.5]=0.5
print('Replace all elements of the said array with .5 which are greater than .5',a)



original array: [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [197]:
a=np.empty((0,3),dtype=int)
print(a)
b1=np.array([[10,20,30]])
b2=np.array([[40,50,60]])
a= np.append(a,b1,axis=0)
a= np.append(a,b2,axis=0)
print('After adding two new arrays:',a)

[]
After adding two new arrays: [[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [207]:
a1=np.array([1,2,3])
b1=np.array([2,3,4])
print('Original array',a1,b1)
c1=np.vstack((a1,b1))

print('Sequence of arrays along a new axis:',c1)

a2=np.array([[1],[2],[3]])
b2=np.array([[2],[3],[4]])

print('Original array',a2,b2)

c2=np.vstack((a2,b2))
print('Sequence of arrays along a new axis:',c2)


Original array [1 2 3] [2 3 4]
Sequence of arrays along a new axis: [[1 2 3]
 [2 3 4]]
Original array [[1]
 [2]
 [3]] [[2]
 [3]
 [4]]
Sequence of arrays along a new axis: [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
